---
title: "Analysis of Past Gov 1005 Projects"
author: "Katelyn Li"
date: "2/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Project 1: Public Transportation & Income in the San Francisco Bay Area

This project examines the relationship between access to public transit and median household income levels in the Bay Area, California. I really liked how the creator chose to include 2 graphs in his "Graphic Data" section: one with the non-adjusted data and one with the adjusted data. As he described in the explainer below the graph, the non-adjusted data hinders our ability to see the correlation between transit access and income, because there is a confounding variable — population. Areas in the Bay Area that have a higher population (such as San Francisco and other large cities) will naturally have a greater density of transit stops, regardless of residents' income levels. By dividing all raw stop counts by their municipal populations the linear relationship between access to public transit and income levels becomes more evident. The grouping (by color) of stops within each metro area on the graph is also useful, as each area can be represented by a different correlation slope. I would have appreciated some analysis of other factors that play into the relationship as well. For example, one question I am left with is: what are the socioeconomic differences between each of the metro areas analyzed (Alameda, Contra Costa, Napa, San Franscisco, San Mateo, Santa Clara, Solano, Sonoma)? Perhaps another graph could have showcased the average household income levels within each area to allow for comparison. Furthermore, I thought the interactive visualization map was very impressive; however, I think some fixes could be made to improve ease of reading. Some labels to describe what each of the numbers mean and what the names of each of the municipalities are would be helpful.

### Project 2: Harvard Friend Group Selection Study

This project looks at the friend group composition among 100 Eliot House residents. It examines factors such as ethnicity, background, legacy status, immigration status, extracurricular activities, and areas of study in order to understand whether students at Harvard self-select for similar qualities when choosing their friends. I really like the premise of this study: it is a very applicable question that I'm sure many students at Harvard have wondered about. I also commend the creators for taking the initiative to collect their own data. Of course, data collection can get into this dangerous area of introduced biases. I'm wondering if this data is truly internally or externally valid. Did the students who participated in the study (Eliot House residents) truly represent the entirety of Harvard? Did the students who participated in the study self-select based on how interested they were in the study questions? Did multiple students in the same friend group take the survey? These factors must be considered when interpreting the data. I also think that the statistical data could have been represented in a more visually appealing manner. Some of the "random friend assignment" graphs seemed to be hand-drawn and I wasn't really sure of the methodology behind how they were created. When using statistics like this, I would like to see some more descriptions of important measures such as p-value. Finally, the axis labels and headings could be tidied up such that the graphs are easier to read; ie. I would have appreciated more descriptive axis labels.